//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauloMorgado.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PauloMorgado.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string ActionCategory {
            get {
                return ResourceManager.GetString("ActionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string AppearanceCategory {
            get {
                return ResourceManager.GetString("AppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string BehaviorCategory {
            get {
                return ResourceManager.GetString("BehaviorCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Changed.
        /// </summary>
        internal static string PropertyChangedCategory {
            get {
                return ResourceManager.GetString("PropertyChangedCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will only become UI active if the mouse is clicked in the client area..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_ActivateOnClientHitOnly {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_ActivateOnClientHitOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will browse clicked links in new window..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_BrowseOpenNewWindow {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_BrowseOpenNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatibility for Microsoft Outlook Express..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_CodepageLinkedFonts {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_CodepageLinkedFonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not enable selection of the text in the form..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_Dialog {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will disable automatic correction of namespaces when editing HTML..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableEditNSFixup {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableEditNSFixup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not add the Help menu item to the container&apos;s menu..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableHelpMenu {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableHelpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableOffscreen {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableOffscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not execute any script when loading pages..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableScriptInactive {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableScriptInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will turn off untrusted protocols..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableUntrustedProtocol {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableUntrustedProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not submit the URL is to the server in UTF-8 encoding..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DisableUTF8Encoding {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DisableUTF8Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will insert the div tag if a return is entered in edit mode..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_DivBlockDefault {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_DivBlockDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires user activation for Microsoft ActiveX controls and Java Applets embedded within a web page..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_EnableActiveXInactivateMode {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_EnableActiveXInactivateMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will enable the AutoComplete feature for forms..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_EnableFormsAutoComplete {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_EnableFormsAutoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation will happen in place..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_EnableInPlaceNavigation {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_EnableInPlaceNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes MSHTML to fire an additional Navigating event when redirect navigations occur..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_EnableRedirectNotification {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_EnableRedirectNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will submit the URL is to the server in UTF-8 encoding..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_EnableUTF8Encoding {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_EnableUTF8Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will use flat scroll bars..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_FlatScrollbars {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_FlatScrollbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that navigation is delegated to the host; otherwise, MSHTML will perform navigation..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_HostNavigates {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_HostNavigates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will enable Input Method Editor (IME) reconversion..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_ImeEnableReconversion {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_ImeEnableReconversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will prevent Web sites in the Internet zone from accessing files in the Local Machine zone..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_LocalMachineAccessCheck {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_LocalMachineAccessCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not use 3-D borders on any frames or framesets..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_No3DBorder {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_No3DBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not display any 3-D border on the outermost frame or frameset..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_No3DOuterBorder {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_No3DOuterBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will disbale PICS ratings..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_NoPics {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_NoPics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not have scroll bars..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_NoScrollBars {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_NoScrollBars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not use themes for pages..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_NoTheme {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_NoTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will consult the host before retrieving..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_OverrideBehaviorFactory {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_OverrideBehaviorFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will use themes for pages..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_Theme {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes MSHTML to create standard Microsoft Win32 &quot;windowed&quot; select and drop-down controls..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_UseWindowedSelectControl {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_UseWindowedSelectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes MSHTML to use the Document Object Model (DOM) to create native &quot;windowless&quot; select controls that can be visually layered under other elements..
        /// </summary>
        internal static string WebBrowserCapabilities_ValueDescription_UseWindowlessSelectControl {
            get {
                return ResourceManager.GetString("WebBrowserCapabilities_ValueDescription_UseWindowlessSelectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the client window size is to be converted to host window size..
        /// </summary>
        internal static string WebBrowserClientToHostWindowDescription {
            get {
                return ResourceManager.GetString("WebBrowserClientToHostWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default behavior..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_Default {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will disable UTF-8 encoding..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_DisableUTF8Encoding {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_DisableUTF8Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will download images from the server..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_DownloadImages {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_DownloadImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will enable UTF-8 encoding..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_EnableUTF8Encoding {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_EnableUTF8Encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will always operate in offline mode..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_ForceOffline {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_ForceOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not download any ActiveX Controls in the document..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoActiveXDownload {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoActiveXDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not execute any ActiveX Controls in the document..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoActiveXRun {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoActiveXRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not execute any behaviors..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoBehaviours {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoBehaviours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not perform any client pull operations..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoClientPull {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoClientPull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not download frames and ignore the frameset..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoFrameDownload {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoFrameDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will suppress HTML Character Sets reflected by meta elements..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoMetaCharSets {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoMetaCharSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will not execute any Java applets..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_NoScripts {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_NoScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will operate in offline mode if not connected to the Internet..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_OfflineIfNotConnected {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_OfflineIfNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will play background sounds associated with the document..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_PlayBackgroundSounds {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_PlayBackgroundSounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will download and display video media..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_PlayVideos {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_PlayVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will force the request through to the server and ignore the proxy..
        /// </summary>
        internal static string WebBrowserDownloadControlOptions_ValueDescription_Resynchronize {
            get {
                return ResourceManager.GetString("WebBrowserDownloadControlOptions_ValueDescription_Resynchronize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the user to browse Web pages inside your form..
        /// </summary>
        internal static string WebBrowserEx_Description {
            get {
                return ResourceManager.GetString("WebBrowserEx_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a document has been completely loaded and initialized..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_DocumentCompleted {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_DocumentCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a navigation operation finishes, is halted, or fails..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_Downloaded {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a navigation operation is beginning..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_Downloading {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a file download is about to occur..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_DownloadingFile {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the FullScreenMode property changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_FullScreenModeChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_FullScreenModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs after a navigation to a link is completed on either a window or frame..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_Navigated {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_Navigated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occours when an error occurs during navigation..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_NavigateError {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_NavigateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before navigation occurs in the given object (on either a window or frameset element)..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_Navigating {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_Navigating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a new window is to be created..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_NewWindow {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_NewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a print template has been created..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_PrintTemplateCreated {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_PrintTemplateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a print template has been destroyed..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_PrintTemplateDestroyed {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_PrintTemplateDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the one of WebBrowserControl&apos;s property values changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_PropertyChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_PropertyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the policy for the specified action is being determined..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_ScriptError {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_ScriptError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when MSHTML when needs to display Help..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_ShowHelp {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_ShowHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the ShowMenuBar property is changed..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_ShowMenuBarChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_ShowMenuBarChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when MSHTML when needs to display a message box..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_ShowMessage {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_ShowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the ShowToolBar property is changed..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_ShowToolBarChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_ShowToolBarChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the status bar text changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_StatusTextChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_StatusTextChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the value of the TheaterMode property changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_TheaterModeChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_TheaterModeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the window of the object is about to be closed by script..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_WindowClosing {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_WindowClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the client window changes its height..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_WindowHeightChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_WindowHeightChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when  the client window left position changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_WindowLeftChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_WindowLeftChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when  the client window top position changes..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_WindowTopChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_WindowTopChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the client window changes its width..
        /// </summary>
        internal static string WebBrowserEx_EventDescription_WindowWidthChanged {
            get {
                return ResourceManager.GetString("WebBrowserEx_EventDescription_WindowWidthChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or Sets a value that indicates whether the object is in full-screen mode or normal window mode..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_FullScreenMode {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_FullScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether 3D borders shouldn&apos;t be used on the outermost frame or frameset only..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_No3DBorder {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_No3DBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether 3D borders shouldn&apos;t be used on any frames or framesets..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_No3DOuterBorder {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_No3DOuterBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the WebBrowserControl is registered as a top-level browser for target name resolution..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_RegisterAsBrowser {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_RegisterAsBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the address bar of the object is visible or hidden..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_ShowAddressBar {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_ShowAddressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether the menu bar is visible..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_ShowMenuBar {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether the status bar is visible..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_ShowStatusBar {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_ShowStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets whether menu bars are visible..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_ShowToolBar {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_ShowToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or Sets a value that indicates whether the control is in theater mode..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_TheaterMode {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_TheaterMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the user agent for the current WebBrowserControl instance..
        /// </summary>
        internal static string WebBrowserEx_PropertyDescription_UserAgent {
            get {
                return ResourceManager.GetString("WebBrowserEx_PropertyDescription_UserAgent", resourceCulture);
            }
        }
    }
}
